In [1]:
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#how it works 

env = gym.make("FrozenLake-v1", render_mode="human")
observation, info = env.reset()

episode_over = False
while not episode_over:
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    episode_over = terminated or truncated

env.close()


In [3]:
#we can render in different mode.

env = gym.make("FrozenLake-v1", render_mode="ansi", is_slippery = True) 
env = env.unwrapped         #because it wrapped in timecounter to give truncated error
observation, info = env.reset()

print(env.render())

action = env.action_space.sample()
state, reward, terminated, truncated, info = env.step(action)
print(env.render())

print(state, reward, terminated)



SFFF
FHFH
FFFH
HFFG

  (Down)
SFFF
FHFH
FFFH
HFFG

4 0.0 False


In [4]:
#this env will give you the transition matrix
env.P[1][1]
# state, action, transion prob, next state, reward, Termination 

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 5, 0.0, True),
 (0.3333333333333333, 2, 0.0, False)]

In [5]:
#Value Iteration
num_states = env.observation_space.n
num_actions = env.action_space.n
gamma = 0.9
epoch = 20

state_value = np.zeros(num_states)
policy = np.zeros(num_states)
for i in range(epoch):
    for state in range(num_states):
        action_value = np.zeros(num_actions)
        for action in range(num_actions):
            # P[1][2] will give info about possible next state
            for TransProb, nextstate, reward, terminated in env.P[state][action]:
                action_value[action] += reward + gamma * TransProb * state_value[nextstate]

        state_value[state] = max(action_value)
        policy[state] = np.argmax(action_value)
    print("*** after epoch ", i+1,"***")
    print("the state value \n", state_value.reshape(4,4))
    print("the best policy \n", policy.reshape(4,4))

*** after epoch  1 ***
the state value 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
the best policy 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]]
*** after epoch  2 ***
the state value 
 [[0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.3  0.  ]
 [0.   0.3  1.39 0.  ]]
the best policy 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 0.]]
*** after epoch  3 ***
the state value 
 [[0.     0.     0.     0.    ]
 [0.     0.     0.09   0.    ]
 [0.     0.18   0.498  0.    ]
 [0.     0.561  1.5853 0.    ]]
the best policy 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 2. 1. 0.]]
*** after epoch  4 ***
the state value 
 [[0.       0.       0.027    0.0081  ]
 [0.       0.       0.1575   0.      ]
 [0.054    0.3339   0.62301  0.      ]
 [0.       0.74406  1.698808 0.      ]]
the best policy 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 2. 1. 0.]]
*** after epoch  5 ***
the state value 
 [[0.         0.0081     0.05778    0.022194

In [6]:
#this works very well